### ISSUE TITLE
로그인 기능

### ISSUE THREAD

**Issue by iolate** [mskims/genie-music-player#10]
로그인 기능이 전체적으로 제대로 작동하지 않는데...
따로 로그인 뷰도 만드셨던데 어떤 의도로 제작하고 계신지 궁금합니다.

1분 미리 듣기 밖에 안되긴 하지만, 로그인이 필수가 아닌 만큼 첫 화면을 로그인 화면으로 강제할 이유도 없을 것 같구요.
소셜 로그인 등을 이용하시는 분들도 있을텐데 그런 부분도 고려가 안되어있고, 그냥 지니 자체 로그인 화면을 그대로 쓰는게 어떨까 건의하고 싶네요.

**Comment by mskims** [comment]
안녕하세요. 일단 의견 남겨주셔서 감사합니다. 적을 내용이 많네요. ㅎ.ㅎ 

일단 이 쓰레드 에선, 로그인 기능이 작동하지 않는 버그에 대해서만 다루도록 하고, 아래 적어주신 내용은 별도의 이슈를 만들겠습니다. 

---

일단 로그인 뷰를 따로 만든 이유는, 아이디 / 비밀번호 저장 기능을 사용하기 위함입니다.

`지니의 로그인 유지 기능(서버 세션)을 활용하면 되는 것 아니냐?` 하고 물어보실 수도 있겠습니다. 더 효율적인 방법 이기도 하고요, 하지만 로그인 정보를 플레이어 렌더러와 노드 메인 쓰레드간에 교환할 효율적인 방법을 찾지 못해 직접 로그인 뷰를 만들어 계정 정보를 저장하게 되었습니다. 시간을 더 할애 해서, #11 에서 진행해보도록 하겠습니다.

소셜 로그인 같은 경우는, 제가 지니 아이디 / 패스워드 로그인 방식만 사용을 했기에, 다른 인증 수단을 테스트 해볼 생각을 못했던 것 같습니다. 이것 역시 #11 에서 진행하겠습니다.

**Comment by mskims** [comment]
#11 이 구현됨에 따라, 수정할 필요가 없어졌습니다.
